name = "LeanDisco"
version = "0.1.0"
defaultTargets = ["leandisco"]

[[lean_lib]]
name = "LeanDisco"

[[lean_lib]]
name = "TestInfiniteNumbers"

[[lean_exe]]
name = "leandisco"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
