name = "LeanDisco"
version = "0.1.0"
defaultTargets = ["leandisco"]

[[lean_lib]]
name = "LeanDisco"

[[lean_lib]]
name = "TestInfiniteNumbers"

[[lean_exe]]
name = "leandisco"
root = "Main"

[[lean_exe]]
name = "runBenchmarks"
root = "RunBenchmarks"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "miniF2F-lean4"
path = "./benchmarks/miniF2F-lean4"
