name = "LeanDisco"
version = "0.1.0"
defaultTargets = ["leandisco"]

[[lean_lib]]
name = "LeanDisco"

[[lean_lib]]
name = "TestInfiniteNumbers"

[[lean_exe]]
name = "leandisco"
root = "Main"

[[lean_exe]]
name = "benchmark"
root = "Benchmark"

[[lean_exe]]
name = "nonminif2f_benchmark"
root = "LeanDisco.NonMiniF2FBenchmark"

[[require]]
name = "mathlib"
scope = "leanprover-community"
